server:
  port: 8080

spring:
  application:
    name: automated-incident-response
  datasource:
    url: jdbc:h2:mem:incidentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.vignesh.incidentresponse: DEBUG

websocket:
  endpoint: /incident-feed
  topic: /topic/incidents

scheduler:
  enabled: true
  incident-check-interval: 30000 # in milliseconds

security:
  jwt:
    secret: changeme-super-secret-key
    expiration: 3600000 # 1 hour

playbook:
  path: classpath:playbooks/